=== focus-shift/jollyday/jollyday-core/src/main/resources/focus_shift.de/jollyday/schema/holiday/holiday.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="https://focus_shift.de/jollyday/schema/holiday"
            xmlns="https://focus_shift.de/jollyday/schema/holiday"
            elementFormDefault="qualified">

  <xsd:simpleType name="Weekday">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="MONDAY"/>
      <xsd:enumeration value="TUESDAY"/>
      <xsd:enumeration value="WEDNESDAY"/>
      <xsd:enumeration value="THURSDAY"/>
      <xsd:enumeration value="FRIDAY"/>
      <xsd:enumeration value="SATURDAY"/>
      <xsd:enumeration value="SUNDAY"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="Month">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="JANUARY"/>
      <xsd:enumeration value="FEBRUARY"/>
      <xsd:enumeration value="MARCH"/>
      <xsd:enumeration value="APRIL"/>
      <xsd:enumeration value="MAY"/>
      <xsd:enumeration value="JUNE"/>
      <xsd:enumeration value="JULY"/>
      <xsd:enumeration value="AUGUST"/>
      <xsd:enumeration value="SEPTEMBER"/>
      <xsd:enumeration value="OCTOBER"/>
      <xsd:enumeration value="NOVEMBER"/>
      <xsd:enumeration value="DECEMBER"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="RelativeToFixed">
    <xsd:complexContent>
      <xsd:extension base="Holiday">
        <xsd:sequence>
          <xsd:choice>
            <xsd:element name="Days" type="xsd:int" minOccurs="0"/>
            <xsd:element name="Weekday" type="Weekday" minOccurs="0"/>
          </xsd:choice>
          <xsd:element name="When" type="When"/>
          <xsd:element name="Date" type="Fixed"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="Holidays">
    <xsd:sequence>
      <xsd:element name="Fixed" type="Fixed" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="RelativeToFixed" type="RelativeToFixed" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="RelativeToWeekdayInMonth" type="RelativeToWeekdayInMonth" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="FixedWeekday" type="FixedWeekdayInMonth" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="ChristianHoliday" type="ChristianHoliday" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="IslamicHoliday" type="IslamicHoliday" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="FixedWeekdayBetweenFixed" type="FixedWeekdayBetweenFixed" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="FixedWeekdayRelativeToFixed" type="FixedWeekdayRelativeToFixed" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="EthiopianOrthodoxHoliday" type="EthiopianOrthodoxHoliday" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="RelativeToEasterSunday" type="RelativeToEasterSunday" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:element name="Configuration" type="Configuration"/>

  <xsd:complexType name="Configuration">
    <xsd:sequence>
      <xsd:element name="Holidays" type="Holidays"/>
      <xsd:element name="Sources" type="Sources" minOccurs="0"/>
      <xsd:element name="SubConfigurations" type="Configuration" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="hierarchy" type="xsd:string"/>
    <xsd:attribute name="description" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="Source">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="of" type="xsd:string"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:complexType name="Sources">
    <xsd:sequence>
      <xsd:element name="Source" type="Source" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="Fixed">
    <xsd:complexContent>
      <xsd:extension base="MoveableHoliday">
        <xsd:attribute name="month" type="Month"/>
        <xsd:attribute name="day">
          <xsd:simpleType>
            <xsd:restriction base="xsd:int">
              <xsd:minInclusive value="1"/>
              <xsd:maxInclusive value="31"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:simpleType name="When">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="BEFORE"/>
      <xsd:enumeration value="AFTER"/>
      <xsd:enumeration value="CLOSEST"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="FixedWeekdayInMonth">
    <xsd:complexContent>
      <xsd:extension base="MoveableHoliday">
        <xsd:attribute name="which" type="Which"/>
        <xsd:attribute name="weekday" type="Weekday"/>
        <xsd:attribute name="month" type="Month"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:simpleType name="Which">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="FIRST"/>
      <xsd:enumeration value="SECOND"/>
      <xsd:enumeration value="THIRD"/>
      <xsd:enumeration value="FOURTH"/>
      <xsd:enumeration value="LAST"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="RelativeToWeekdayInMonth">
    <xsd:complexContent>
      <xsd:extension base="Holiday">
        <xsd:sequence>
          <xsd:element name="FixedWeekday" type="FixedWeekdayInMonth"/>
        </xsd:sequence>
        <xsd:attribute name="weekday" type="Weekday"/>
        <xsd:attribute name="when" type="When"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="IslamicHoliday">
    <xsd:complexContent>
      <xsd:extension base="MoveableHoliday">
        <xsd:attribute name="type" type="IslamicHolidayType"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:simpleType name="IslamicHolidayType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="NEWYEAR"/>
      <xsd:enumeration value="ASCHURA"/>
      <xsd:enumeration value="TASUA"/>
      <xsd:enumeration value="MAWLID_AN_NABI"/>
      <xsd:enumeration value="LAILAT_AL_MIRAJ"/>
      <xsd:enumeration value="LAILAT_AL_BARAT"/>
      <xsd:enumeration value="RAMADAN"/>
      <xsd:enumeration value="JUMUATUL_WIDA"/>
      <xsd:enumeration value="LAILAT_AL_QADR"/>
      <xsd:enumeration value="RAMADAN_END"/>
      <xsd:enumeration value="ID_AL_FITR"/>
      <xsd:enumeration value="ID_AL_FITR_2"/>
      <xsd:enumeration value="ID_AL_FITR_3"/>
      <xsd:enumeration value="ARAFAAT"/>
      <xsd:enumeration value="ID_UL_ADHA"/>
      <xsd:enumeration value="ID_UL_ADHA_2"/>
      <xsd:enumeration value="ID_UL_ADHA_3"/>
      <xsd:enumeration value="ID_AL_GHADIR"/>
      <xsd:enumeration value="GRAND_MAGAL_OF_TOUBA"/>
      <xsd:enumeration value="QAUMEE_DHUVAS"/>
      <xsd:enumeration value="EMBRACING_OF_ISLAM_DAY"/>
      <xsd:enumeration value="ARBAEEN"/>
      <xsd:enumeration value="DEATH_OF_MUHAMMAD_AND_HASAN_MOJTABA"/>
      <xsd:enumeration value="DEATH_OF_IMAM_REZA"/>
      <xsd:enumeration value="DEATH_OF_IMAM_HASAN_ASKARI"/>
      <xsd:enumeration value="BIRTH_OF_MUHAMMAD_AND_IMAM_SADIQ"/>
      <xsd:enumeration value="DEATH_OF_FATIMA"/>
      <xsd:enumeration value="BIRTH_OF_IMAM_ALI"/>
      <xsd:enumeration value="DEATH_OF_IMAM_ALI"/>
      <xsd:enumeration value="DEATH_OF_IMAM_SADIQ"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="ChronologyType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="JULIAN"/>
      <xsd:enumeration value="GREGORIAN"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="ChristianHoliday">
    <xsd:complexContent>
      <xsd:extension base="MoveableHoliday">
        <xsd:attribute name="type" type="ChristianHolidayType"/>
        <xsd:attribute name="chronology" type="ChronologyType"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:simpleType name="HolidayType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="PUBLIC_HOLIDAY"/>
      <xsd:enumeration value="BANK_HOLIDAY"/>
      <xsd:enumeration value="OBSERVANCE"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="ChristianHolidayType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="GOOD_FRIDAY"/>
      <xsd:enumeration value="EASTER_MONDAY"/>
      <xsd:enumeration value="ASCENSION_DAY"/>
      <xsd:enumeration value="WHIT_MONDAY"/>
      <xsd:enumeration value="CORPUS_CHRISTI"/>
      <xsd:enumeration value="PALM_SUNDAY"/>
      <xsd:enumeration value="MAUNDY_THURSDAY"/>
      <xsd:enumeration value="ASH_WEDNESDAY"/>
      <xsd:enumeration value="MARDI_GRAS"/>
      <xsd:enumeration value="GENERAL_PRAYER_DAY"/>
      <xsd:enumeration value="CLEAN_MONDAY"/>
      <xsd:enumeration value="SHROVE_MONDAY"/>
      <xsd:enumeration value="PENTECOST"/>
      <xsd:enumeration value="CARNIVAL"/>
      <xsd:enumeration value="EASTER_SATURDAY"/>
      <xsd:enumeration value="EASTER_TUESDAY"/>
      <xsd:enumeration value="SACRED_HEART"/>
      <xsd:enumeration value="EASTER"/>
      <xsd:enumeration value="PENTECOST_MONDAY"/>
      <xsd:enumeration value="WHIT_SUNDAY"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="FixedWeekdayBetweenFixed">
    <xsd:complexContent>
      <xsd:extension base="Holiday">
        <xsd:sequence>
          <xsd:element name="from" type="Fixed"/>
          <xsd:element name="to" type="Fixed"/>
        </xsd:sequence>
        <xsd:attribute name="weekday" type="Weekday"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="Holiday" abstract="true">
    <xsd:attribute name="validFrom" type="xsd:int"/>
    <xsd:attribute name="validTo" type="xsd:int"/>
    <xsd:attribute name="every" type="HolidayCycleType" default="EVERY_YEAR"/>
    <xsd:attribute name="descriptionPropertiesKey" type="xsd:string"/>
    <xsd:attribute name="localizedType" type="HolidayType" default="PUBLIC_HOLIDAY"/>
  </xsd:complexType>

  <xsd:simpleType name="Substituted">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="ON_SATURDAY"/>
      <xsd:enumeration value="ON_SUNDAY"/>
      <xsd:enumeration value="ON_WEEKEND"/>
      <xsd:enumeration value="ON_TUESDAY"/>
      <xsd:enumeration value="ON_WEDNESDAY"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="With">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="NEXT"/>
      <xsd:enumeration value="PREVIOUS"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="MovingCondition">
    <xsd:attribute name="substitute" type="Weekday"/>
    <xsd:attribute name="with" type="With"/>
    <xsd:attribute name="weekday" type="Weekday"/>
  </xsd:complexType>

  <xsd:complexType name="MoveableHoliday" abstract="true">
    <xsd:complexContent>
      <xsd:extension base="Holiday">
        <xsd:sequence>
          <xsd:element name="MovingCondition" type="MovingCondition" maxOccurs="unbounded" minOccurs="0"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="EthiopianOrthodoxHoliday">
    <xsd:complexContent>
      <xsd:extension base="Holiday">
        <xsd:attribute name="type" type="EthiopianOrthodoxHolidayType"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:simpleType name="EthiopianOrthodoxHolidayType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="TIMKAT"/>
      <xsd:enumeration value="ENKUTATASH"/>
      <xsd:enumeration value="MESKEL"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="FixedWeekdayRelativeToFixed">
    <xsd:complexContent>
      <xsd:extension base="Holiday">
        <xsd:sequence>
          <xsd:element name="day" type="Fixed"/>
        </xsd:sequence>
        <xsd:attribute name="which" type="Which"/>
        <xsd:attribute name="weekday" type="Weekday"/>
        <xsd:attribute name="when" type="When"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:simpleType name="HolidayCycleType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="EVERY_YEAR"/>
      <xsd:enumeration value="TWO_YEARS"/>
      <xsd:enumeration value="THREE_YEARS"/>
      <xsd:enumeration value="FOUR_YEARS"/>
      <xsd:enumeration value="FIVE_YEARS"/>
      <xsd:enumeration value="SIX_YEARS"/>
      <xsd:enumeration value="ODD_YEARS"/>
      <xsd:enumeration value="EVEN_YEARS"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="RelativeToEasterSunday">
    <xsd:complexContent>
      <xsd:extension base="Holiday">
        <xsd:sequence>
          <xsd:element name="chronology" type="ChronologyType"/>
          <xsd:element name="days" type="xsd:int"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
</xsd:schema>

=== focus-shift/jollyday/jollyday-core/src/main/resources/holidays/Holidays_pl.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration hierarchy="pl" description="Poland"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <!-- Ustawa z dnia 18 stycznia 1951 r. o dniach wolnych od pracy (Dz.U. 1951 nr 4 poz. 28) and its amendments -->
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <!-- Removed by Dz.U. 1960 nr 51 poz. 297 (in force 24 Nov 1960), restored by Dz.U. 2010 nr 224 poz. 1459 (in force 1 Jan 2011) -->
    <Fixed month="JANUARY" day="6" validTo="1960" descriptionPropertiesKey="EPIPHANY"/>
    <Fixed month="JANUARY" day="6" validFrom="2011" descriptionPropertiesKey="EPIPHANY"/>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <!-- Restored by Dz.U. 1990 nr 28 poz. 160 (in force 28 Apr 1990) -->
    <Fixed month="MAY" day="3" validFrom="1990" descriptionPropertiesKey="CONSTITUTION_DAY"/>
    <!-- Day off since the act of 22 July 1945 (Dz.U. 1945 nr 32 poz. 194, with effect from 22 Jul 1945),
         abolished by Dz.U. 1990 nr 28 poz. 159 (in force 28 Apr 1990) -->
    <Fixed month="JULY" day="22" validFrom="1945" validTo="1989" descriptionPropertiesKey="NATIONAL_DAY_OF_REBIRTH_OF_POLAND"/>
    <!-- Removed by Dz.U. 1960 nr 51 poz. 297 (in force 24 Nov 1960), restored by Dz.U. 1989 nr 29 poz. 154 (in force 23 May 1989) -->
    <Fixed month="AUGUST" day="15" validTo="1960" descriptionPropertiesKey="ASSUMPTION_DAY"/>
    <Fixed month="AUGUST" day="15" validFrom="1989" descriptionPropertiesKey="ASSUMPTION_DAY"/>
    <Fixed month="NOVEMBER" day="1" descriptionPropertiesKey="ALL_SAINTS"/>
    <!-- Added by Dz.U. 1989 nr 29 poz. 154 (in force 23 May 1989) -->
    <Fixed month="NOVEMBER" day="11" validFrom="1989" descriptionPropertiesKey="INDEPENDENCE_DAY"/>
    <!-- Added by Dz.U. 2024 poz. 1965 (in force 1 Feb 2025) -->
    <Fixed month="DECEMBER" day="24" validFrom="2025" descriptionPropertiesKey="CHRISTMAS_EVE"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
    <Fixed month="DECEMBER" day="26" descriptionPropertiesKey="STEPHENS"/>
    <ChristianHoliday type="EASTER"/>
    <ChristianHoliday type="EASTER_MONDAY"/>
    <ChristianHoliday type="PENTECOST"/>
    <ChristianHoliday type="CORPUS_CHRISTI"/>
  </Holidays>

  <Sources>
    <Source>https://isap.sejm.gov.pl/isap.nsf/DocDetails.xsp?id=WDU19510040028</Source>
    <Source>https://en.wikipedia.org/wiki/Public_holidays_in_Poland</Source>
    <Source of="ISO 3166">https://www.iso.org/obp/ui/#iso:code:3166:PL</Source>
    <Source of="ISO 3166-2">https://en.wikipedia.org/wiki/ISO_3166-2:PL</Source>
  </Sources>

  <SubConfigurations hierarchy="02" description="Dolnośląskie">
    <Holidays/>
  </SubConfigurations>

  <SubConfigurations hierarchy="04" description="Kujawsko-Pomorskie">
    <Holidays/>
  </SubConfigurations>

  <SubConfigurations hierarchy="06" description="Lubelskie">
    <Holidays/>
  </SubConfigurations>

  <SubConfigurations hierarchy="08" description="Lubuskie">
    <Holidays/>
  </SubConfigurations>

  <SubConfigurations hierarchy="10" description="Łódzkie">
    <Holidays/>
  </SubConfigurations>

  <SubConfigurations hierarchy="12" description="Małopolskie">
    <Holidays/>
  </SubConfigurations>

  <SubConfigurations hierarchy="14" description="Mazowieckie">
    <Holidays/>
  </SubConfigurations>

  <SubConfigurations hierarchy="16" description="Opolskie">
    <Holidays/>
  </SubConfigurations>

  <SubConfigurations hierarchy="18" description="Podkarpackie">
    <Holidays/>
  </SubConfigurations>

  <SubConfigurations hierarchy="20" description="Podlaskie">
    <Holidays/>
  </SubConfigurations>

  <SubConfigurations hierarchy="22" description="Pomorskie">
    <Holidays/>
  </SubConfigurations>

  <SubConfigurations hierarchy="24" description="Śląskie">
    <Holidays/>
  </SubConfigurations>

  <SubConfigurations hierarchy="26" description="Świętokrzyskie">
    <Holidays/>
  </SubConfigurations>

  <SubConfigurations hierarchy="28" description="Warmińsko-Mazurskie">
    <Holidays/>
  </SubConfigurations>

  <SubConfigurations hierarchy="30" description="Wielkopolskie">
    <Holidays/>
  </SubConfigurations>

  <SubConfigurations hierarchy="32" description="Zachodniopomorskie">
    <Holidays/>
  </SubConfigurations>

</Configuration>

=== focus-shift/jollyday/jollyday-core/src/main/resources/holidays/Holidays_lb.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration hierarchy="lb" description="Lebanon"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">

  <Holidays>
    <!-- Fixed date national holidays -->
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="JANUARY" day="6" descriptionPropertiesKey="EPIPHANY"/>
    <Fixed month="FEBRUARY" day="9" descriptionPropertiesKey="SAINT_MARONS"/>
    <Fixed month="FEBRUARY" day="14" descriptionPropertiesKey="HARIRI_MEMORIAL_DAY"/>
    <Fixed month="MARCH" day="25" descriptionPropertiesKey="ANNUNCIATION"/>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <Fixed month="MAY" day="25" descriptionPropertiesKey="RESISTANCE_LIBERATION_DAY"/>
    <Fixed month="AUGUST" day="15" descriptionPropertiesKey="ASSUMPTION_DAY"/>
    <Fixed month="NOVEMBER" day="22" descriptionPropertiesKey="INDEPENDENCE_DAY"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>

    <!-- Moveable Christian holidays (Gregorian/Western chronology) -->
    <ChristianHoliday type="GOOD_FRIDAY"/>
    <ChristianHoliday type="EASTER"/>

    <!-- Islamic holidays (lunar calendar driven) -->
    <IslamicHoliday type="NEWYEAR"/>
    <IslamicHoliday type="ASCHURA"/>
    <IslamicHoliday type="MAWLID_AN_NABI"/>
    <IslamicHoliday type="ID_AL_FITR"/>
    <IslamicHoliday type="ID_UL_ADHA"/>
  </Holidays>

  <Sources>
    <Source>https://en.wikipedia.org/wiki/Public_holidays_in_Lebanon</Source>
  </Sources>
</Configuration>

=== focus-shift/jollyday/jollyday-core/src/main/resources/holidays/Holidays_gh.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration hierarchy="gh" description="Ghana"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>
    <Fixed month="JANUARY" day="7" descriptionPropertiesKey="CONSTITUTION_DAY">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>
    <Fixed month="MARCH" day="6" descriptionPropertiesKey="INDEPENDENCE_DAY">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>
    <Fixed month="JULY" day="1" descriptionPropertiesKey="REPUBLIC_DAY">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>
    <Fixed month="SEPTEMBER" day="21" descriptionPropertiesKey="FOUNDERS_DAY">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>
    <Fixed month="DECEMBER" day="26" descriptionPropertiesKey="BOXING_DAY">
      <MovingCondition substitute="MONDAY" with="NEXT" weekday="TUESDAY"/>
    </Fixed>

    <FixedWeekday which="FIRST" weekday="FRIDAY" month="DECEMBER" descriptionPropertiesKey="FARMERS_DAY">
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </FixedWeekday>

    <ChristianHoliday type="GOOD_FRIDAY"/>
    <ChristianHoliday type="EASTER_MONDAY"/>

    <IslamicHoliday type="ID_AL_FITR"/>
    <IslamicHoliday type="ID_UL_ADHA"/>
  </Holidays>

  <Sources>
    <Source>https://en.wikipedia.org/wiki/Public_holidays_in_Ghana</Source>
    <Source of="ISO 3166">https://www.iso.org/obp/ui/#iso:code:3166:GH</Source>
    <Source of="ISO 3166-2">https://en.wikipedia.org/wiki/ISO_3166-2:GH</Source>
  </Sources>

  <SubConfigurations hierarchy="aa" description="Greater Accra">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="af" description="Ahafo">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="ah" description="Ashanti">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="be" description="Bono East">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="bo" description="Bono">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="cp" description="Central">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="ep" description="Eastern">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="ne" description="North East">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="np" description="Northern">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="ot" description="Oti">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="sv" description="Savannah">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="tv" description="Volta">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="ue" description="Upper East">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="uw" description="Upper West">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="wn" description="Western North">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="wp" description="Western">
    <Holidays/>
  </SubConfigurations>
</Configuration>

=== focus-shift/jollyday/jollyday-core/src/main/resources/holidays/Holidays_be.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration hierarchy="be" description="Belgium"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <Fixed month="JULY" day="21" descriptionPropertiesKey="NATIONAL_DAY"/>
    <Fixed month="AUGUST" day="15" descriptionPropertiesKey="ASSUMPTION_DAY"/>
    <Fixed month="NOVEMBER" day="1" descriptionPropertiesKey="ALL_SAINTS"/>
    <Fixed month="NOVEMBER" day="2" descriptionPropertiesKey="ALL_SOULS" localizedType="OBSERVANCE"/>
    <Fixed month="NOVEMBER" day="11" descriptionPropertiesKey="ARMISTICE"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
    <Fixed month="NOVEMBER" day="15" descriptionPropertiesKey="KINGS_FEAST" localizedType="OBSERVANCE" />
    <Fixed month="DECEMBER" day="31" descriptionPropertiesKey="NEW_YEARS_EVE" localizedType="OBSERVANCE"/>
    <ChristianHoliday type="EASTER"/>
    <ChristianHoliday type="EASTER_MONDAY"/>
    <ChristianHoliday type="ASCENSION_DAY"/>
    <ChristianHoliday type="PENTECOST"/>
    <ChristianHoliday type="PENTECOST_MONDAY"/>
  </Holidays>

  <Sources>
    <Source>https://en.wikipedia.org/wiki/Public_holidays_in_Belgium</Source>
    <Source of="ISO 3166">https://www.iso.org/obp/ui/#iso:code:3166:BE</Source>
    <Source of="ISO 3166-2">https://en.wikipedia.org/wiki/ISO_3166-2:BE</Source>
  </Sources>

  <SubConfigurations hierarchy="bru" description="Brussels">
    <Holidays/>
  </SubConfigurations>

  <SubConfigurations hierarchy="van" description="Antwerp">
    <Holidays/>
  </SubConfigurations>

  <SubConfigurations hierarchy="vbr" description="Flemish Brabant">
    <Holidays/>
  </SubConfigurations>

  <SubConfigurations hierarchy="vlg" description="Flanders">
    <Holidays/>
  </SubConfigurations>

  <SubConfigurations hierarchy="vli" description="Limburg">
    <Holidays/>
  </SubConfigurations>

  <SubConfigurations hierarchy="vov" description="East Flanders">
    <Holidays/>
  </SubConfigurations>

  <SubConfigurations hierarchy="vwv" description="West Flanders">
    <Holidays/>
  </SubConfigurations>

  <SubConfigurations hierarchy="wal" description="Wallonia">
    <Holidays/>
  </SubConfigurations>

  <SubConfigurations hierarchy="wbr" description="Walloon Brabant">
    <Holidays/>
  </SubConfigurations>

  <SubConfigurations hierarchy="wht" description="Hainaut">
    <Holidays/>
  </SubConfigurations>

  <SubConfigurations hierarchy="wlg" description="Liège">
    <Holidays/>
  </SubConfigurations>

  <SubConfigurations hierarchy="wlx" description="Luxembourg">
    <Holidays/>
  </SubConfigurations>

  <SubConfigurations hierarchy="wna" description="Namur">
    <Holidays/>
  </SubConfigurations>

</Configuration>

=== focus-shift/jollyday/jollyday-tests/src/test/resources/holidays/Holidays_test_sg_2017.xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration hierarchy="sg" description="Singapore"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="2" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="JANUARY" day="28" descriptionPropertiesKey="CHINESE_NEW_YEAR"/>
    <Fixed month="JANUARY" day="30" descriptionPropertiesKey="CHINESE_NEW_YEAR"/>
    <Fixed month="APRIL" day="14" descriptionPropertiesKey="christian.GOOD_FRIDAY"/>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <Fixed month="MAY" day="10" descriptionPropertiesKey="VESAK_DAY"/>
    <Fixed month="JUNE" day="26" descriptionPropertiesKey="HARI_RAYA_PUASA"/>
    <Fixed month="AUGUST" day="9" descriptionPropertiesKey="NATIONAL_DAY"/>
    <Fixed month="SEPTEMBER" day="1" descriptionPropertiesKey="HARI_RAYA_HAJI"/>
    <Fixed month="OCTOBER" day="18" descriptionPropertiesKey="DEEPAVALI"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
  </Holidays>
</Configuration>

=== focus-shift/jollyday/jollyday-test/src/test/resources/holidays/Holidays_test_ua_2015.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="ua" description="Ukraine"
                   xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
    <tns:Holidays>
        <tns:Fixed month="JANUARY" day="1"/>
        <tns:Fixed month="JANUARY" day="7"/>
        <tns:Fixed month="MARCH" day="9"/>
        <tns:Fixed month="APRIL" day="13"/>
        <tns:Fixed month="MAY" day="1"/>
        <tns:Fixed month="MAY" day="4"/>
        <tns:Fixed month="MAY" day="11"/>
        <tns:Fixed month="JUNE" day="1"/>
        <tns:Fixed month="JUNE" day="29"/>
        <tns:Fixed month="AUGUST" day="24"/>
        <tns:Fixed month="OCTOBER" day="14"/>
    </tns:Holidays>
</tns:Configuration>
